config/routes.rb
Trendveller::Application.routes.draw do

  root :to => "lists#home"
  get "/results", :to => "lists#results", :as => :results
  get "/shops", :to => "lists#shops", :as => :shops
  get "/restaurants", :to => "lists#restaurants", :as => :restaurants
  get "/entertainments", :to => "lists#entertainments", :as => :entertainments
  get "/hotels", :to => "lists#hotels", :as => :hotels
  get "/feeds/index"
  get "/place", :to => "lists#place"
  get "/mobile", :to => "pages#new"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  def index
    @data = Request.get_request("#{Constant::POPULAR}?client_id=#{APP_CONFIG['iclient_id']}")
    render :partial => 'content' and return if request.xhr?
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def home
  end

  def results
    session[:search_results] = request.url
    @address = params[:address] || session[:address]
    session[:address] = params[:address] if params[:address]
    coordinates = Geocoder.coordinates(@address)
    client = Foursquare2::Client.new(:client_id => ENV["CLIENT_ID"], :client_secret => ENV["CLIENT_SECRET"])
    @venues = client.trending_venues(coordinates.join(","),{:limit => 100, :radius => 10000 }).venues

    respond_to do |format|
      format.html
      format.json { render :json => @venues }
    end

  end

  def shops
    session[:search_results] = request.url
    @address = params[:address] || session[:address]
    session[:address] = params[:address] if params[:address]
    coordinates = Geocoder.coordinates(@address)
    client = Foursquare2::Client.new(:client_id => ENV["CLIENT_ID"], :client_secret => ENV["CLIENT_SECRET"])
    @venues = client.trending_venues(coordinates.join(","),{:limit => 100, :radius => 10000 }).venues

    @venues = @venues.select { |v| v['categories'].any? { |cat| cat['parents'].join("") =~ /Shops/ } }

    respond_to do |format|
      format.html
      format.json { render :json => @venues }
    end

  end

  def restaurants
    session[:search_results] = request.url
    @address = params[:address] || session[:address]
    session[:address] = params[:address] if params[:address]
    coordinates = Geocoder.coordinates(@address)
    client = Foursquare2::Client.new(:client_id => ENV["CLIENT_ID"], :client_secret => ENV["CLIENT_SECRET"])
    @venues = client.trending_venues(coordinates.join(","),{:limit => 100, :radius => 10000 }).venues

    @venues = @venues.select { |v| v['categories'].any? { |cat| cat['parents'].join("") =~ /Food/ or cat['parents'].join("") =~ /Nightlife/ } }

    respond_to do |format|
      format.html
      format.json { render :json => @venues }
    end

  end

  def entertainments
    session[:search_results] = request.url
    @address = params[:address] || session[:address]
    session[:address] = params[:address] if params[:address]
    coordinates = Geocoder.coordinates(@address)
    client = Foursquare2::Client.new(:client_id => ENV["CLIENT_ID"], :client_secret => ENV["CLIENT_SECRET"])
    @venues = client.trending_venues(coordinates.join(","),{:limit => 100, :radius => 10000 }).venues

    @venues = @venues.select { |v| v['categories'].any? { |cat| cat['parents'].join("") =~ /Arts & Entertainment/ } }

    respond_to do |format|
      format.html
      format.json { render :json => @venues }
    end

  end

  def hotels
    session[:search_results] = request.url
    @address = params[:address] || session[:address]
    session[:address] = params[:address] if params[:address]
    coordinates = Geocoder.coordinates(@address)
    client = Foursquare2::Client.new(:client_id => ENV["CLIENT_ID"], :client_secret => ENV["CLIENT_SECRET"])
    @venues = client.trending_venues(coordinates.join(","),{:limit => 100, :radius => 10000 }).venues

    @venues = @venues.select { |v| v['categories'].any? { |cat| cat['parents'].join("") =~ /Travel & Transport/  } }

    respond_to do |format|
      format.html
      format.json { render :json => @venues }
    end

  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/feeds/_content.html.erb
<div id="disp">
  <% @data["data"].each_with_index do |data,i| %>
    <div class="grid_6 omega">
      <div class="image-contain">
        <a  class="fancybox_<%= i %>" href="<%= data["images"]["standard_resolution"]["url"] %>" id="detail<%= i %>" title="<%= data["caption"]["text"].force_encoding("UTF-8") rescue "" %>"><img src="<%= data["images"]["standard_resolution"]["url"] %>" style="width:97%" ></a>
      </div>
      <div class="des-bar">
        <div class="bar-font"><%= data["comments"]["count"]  %> Comments <%= data["likes"]["count"] %> Likes</div>
      </div>
      <div id="someHtml_<%= i %>" style="display:none;">
        <img class="ri" src="<%= data["images"]["standard_resolution"]["url"] %>" >
        <!-- <%#= data["caption"]["text"].force_encoding("UTF-8") rescue "" %> -->
        <div style="background-color: #1E8E77;color: white;border: 2px solid;border-radius: 3px;box-shadow: 0 3px 6px rgba(0,0,0,0.9);font-weight: bold;">
          <% if data["caption"].present? %>
            <div>
              <img src="<%= data["caption"]["from"]["profile_picture"] rescue '' %>" style="width: 15%;border-radius: 66%;margin-left: 44%;" >
              <div style="text-align:center;"><%= data["caption"]["from"]["username"] %></div>
            </div>
          <% end %>

          <div style="text-align:center;"><%= data["comments"]["count"]  %>Comments <%= data["likes"]["count"] %> Likes</div>
         </div>
         <div>
          <div>
            <% data["comments"]["data"][0..3].each do |comment| %>
              <div style="border-bottom: 1px solid;">
                <%if @current_user.present? %>
                  <a href="/user-info/?id=<%= comment["from"]["id"] %>"><img src="<%= comment["from"]["profile_picture"] %>" style="width: 9%;"><br/></a>
                  <% else %>
                    <img src="<%= comment["from"]["profile_picture"] %>" style="width: 9%;"><br/>
                  <% end %>
                <%= comment["from"]["username"] %>
                <p style="max-width: 35%;float:right; margin: -4% 46% 0% 0"><%= comment["text"] %></p>
            </div>
              <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/feeds/index.html.erb
FEEDS

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TrendVel</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <script type="text/javascript">
    jQuery(document).ready(function($) {
        JQUERY4U.TWITTER.init();
    });
  </script>
  <script type="text/javascript">
    var locale = '<%= I18n.locale %>';
  </script>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
</head>
<body>

<body id="bg_yellow">

<%= yield %>

</body>
</html>

app/views/lists/entertainments.html.erb
<div class="container">
  <h2>The top places right now</h2>
  <% rank = 1 %>
  <% @venues.each do |v| %>
    <div class="results">
      <div id="rank">
        <%= rank %>
      </div>

      <div class="result">
        <div class="current_checkins">
          <p>Current <br>
            Check-ins</p>
          <p><%= v["hereNow"]["count"] %></p>
        </div>
        <div class="venue_details">
          <div><img src="<%= v["categories"][0]["icon"] %>"></div>
          <p><a href= "<%= v["canonicalUrl"] %>" target="blank"><%= v["name"] %></a></p>
          <p><%= v["location"]["address"] %></p>
          <p>Total Check-ins: <%= v["stats"]["checkinsCount"] %></p>
          <p><%= link_to "Social talk about this", "https://twitter.com/search?q=#{v["name"]}", :target => "_blank" %></p>
        </div>
            <!-- <p id="save">Get direction</p> -->
            <p><div class="btn btn-success"><%= link_to "Take me there ", "https://maps.google.com/maps/myplaces?ll=#{v["location"]["lat"]},#{v["location"]["lng"]}", :target => "_blank" %><i class="icon-map-marker icon-white"></i>
            </div></p>
      </div>
      <% rank += 1 %>
    </div>
  <% end %>
</div>

<div class="row">
  <div class="span7 offset5">
    <%= link_to "Back", :back %>
  </div>
</div>

app/views/lists/home.html.erb
<div class="container">
  <h1>Where is hot now?</h1>
  <div class="rule_yellow" style="width:570px"></div>
  <div class="rule_white" style="width:570px"></div>

  <div id="search_box">
    <form action="/results" method="get">
    <input type="text" name="address" placeholder="Enter city or an address"/>
    <button class="btn_blue"> search </button>
  </div>

<div class="container">
  <div class="span6 offset3">
  <%= link_to image_tag("https://foursquare.com/img/categories_v2/travel/default_bg_64.png"), hotels_path(:address => "Bangkok")  %>
<%= link_to image_tag("https://foursquare.com/img/categories_v2/food/default_bg_64.png"), restaurants_path(:address => "Bangkok")  %>
<%= link_to image_tag("https://foursquare.com/img/categories_v2/arts_entertainment/default_bg_64.png"), entertainments_path(:address => "Bangkok")  %>
<%= link_to image_tag("https://foursquare.com/img/categories_v2/shops/default_bg_64.png"), shops_path(:address => "Bangkok")  %>
</div>
</div>

</div>

<div class="container">
  <div class="span6">
    <div id="wrap">
            <div class="header-container">
                <header class="wrapper clearfix">
                  <div class="ctaColumn">
                    <h1>TrendVel Mobile</h1>
                    </div>

                    <div class="fader">
                      <div class="flexslider1">
                        <ul class="slides">
                          <!-- INSERT IPHONE SLIDE  -->
                          <li><%= image_tag("p1.jpg")%></li>
                          <!-- INSERT IPHONE SLIDE  -->
                          <li><%= image_tag("p2.jpg")%></li>
                          <!-- INSERT IPHONE SLIDE  -->
                          <li><%= image_tag("p3.jpg")%></li>
                        </ul>
                      </div>
                    </div>

                </header>
            </div>
    </div>
  </div>

    <div class="span6">

      <h1>Unleash your travel!</h1>
      <p><h3>Trendvel</h3> finds the coolest place in your location with realtime social</p>

      <p>So what are you waiting for? Start your travel now.</p>
      <ul>
        <li><h3>Step 1: finds the coolest place.</h3></li>
        <li><h3 style="margin-top:10px;">Step 2: Get direction.</h3></li>
        <li><h3 style="margin-top:10px;">Step 3: Check-in your trip and share your achievement.</h3></li>
      </ul>
    </div>

  </div>


  <footer class="footer">
      <div class="container">
        <p>Designed and built with all the love in the world by <a href="http://locaze.co" target="_blank">@locaze</a>.</p>
      </div>
  </footer>

</div>

app/views/lists/hotels.html.erb
<div class="container">
  <h2>The top places right now</h2>
  <% rank = 1 %>
  <% @venues.each do |v| %>
    <div class="results">
      <div id="rank">
        <%= rank %>
      </div>

      <div class="result">
        <div class="current_checkins">
          <p>Current <br>
            Check-ins</p>
          <p><%= v["hereNow"]["count"] %></p>
        </div>
        <div class="venue_details">
          <div><img src="<%= v["categories"][0]["icon"] %>"></div>
          <p><a href= "<%= v["canonicalUrl"] %>" target="blank"><%= v["name"] %></a></p>
          <p><%= v["location"]["address"] %></p>
          <p>Total Check-ins: <%= v["stats"]["checkinsCount"] %></p>
          <p><%= link_to "Social talk about this", "https://twitter.com/search?q=#{v["name"]}", :target => "_blank" %></p>
        </div>
            <!-- <p id="save">Get direction</p> -->
            <p><div class="btn btn-success"><%= link_to "Take me there ", "https://maps.google.com/maps/myplaces?ll=#{v["location"]["lat"]},#{v["location"]["lng"]}", :target => "_blank" %><i class="icon-map-marker icon-white"></i>
            </div></p>
      </div>
      <% rank += 1 %>
    </div>
  <% end %>
</div>


<div class="row">
  <div class="span7 offset5">
    <%= link_to "Back", :back %>
  </div>
</div>

app/views/lists/place.html.erb
<div class="result">
Here
</div>

app/views/lists/restaurants.html.erb
<div class="container">
  <h2>The top places right now</h2>
  <% rank = 1 %>
  <% @venues.each do |v| %>
    <div class="results">
      <div id="rank">
        <%= rank %>
      </div>

      <div class="result">
        <div class="current_checkins">
          <p>Current <br>
            Check-ins</p>
          <p><%= v["hereNow"]["count"] %></p>
        </div>
        <div class="venue_details">
          <div><img src="<%= v["categories"][0]["icon"] %>"></div>
          <p><a href= "<%= v["canonicalUrl"] %>" target="blank"><%= v["name"] %></a></p>
          <p><%= v["location"]["address"] %></p>
          <p>Total Check-ins: <%= v["stats"]["checkinsCount"] %></p>
          <p><%= link_to "Social talk about this", "https://twitter.com/search?q=#{v["name"]}", :target => "_blank" %></p>
        </div>
            <!-- <p id="save">Get direction</p> -->
            <p><div class="btn btn-success"><%= link_to "Take me there ", "https://maps.google.com/maps/myplaces?ll=#{v["location"]["lat"]},#{v["location"]["lng"]}", :target => "_blank" %><i class="icon-map-marker icon-white"></i>
            </div></p>
      </div>
      <% rank += 1 %>
    </div>
  <% end %>
</div>

<div class="row">
  <div class="span7 offset5">
    <%= link_to "Back", :back %>
  </div>
</div>

app/views/lists/results.html.erb
<div class="container">
  <h2>The top places right now</h2>
  <% rank = 1 %>
  <% @venues.each do |v| %>
    <div class="results">
      <div id="rank">
        <%= rank %>
      </div>

      <div class="result">
        <div class="current_checkins">
          <p>Current <br>
            Check-ins</p>
          <p><%= v["hereNow"]["count"] %></p>
        </div>
        <div class="venue_details">
          <div><img src="<%= v["categories"][0]["icon"] %>"></div>
          <p><a href= "<%= v["canonicalUrl"] %>" target="blank"><%= v["name"] %></a></p>
          <p><%= v["location"]["address"] %></p>
          <p>Total Check-ins: <%= v["stats"]["checkinsCount"] %></p>
          <p><%= link_to "Social talk about this", "https://twitter.com/search?q=#{v["name"]}", :target => "_blank" %></p>
        </div>
            <!-- <p id="save">Get direction</p> -->
            <p><div class="btn btn-success"><%= link_to "Take me there ", "https://maps.google.com/maps/myplaces?ll=#{v["location"]["lat"]},#{v["location"]["lng"]}", :target => "_blank" %><i class="icon-map-marker icon-white"></i>
            </div></p>
      </div>
      <% rank += 1 %>
    </div>
  <% end %>
</div>

<div class="row">
  <div class="span7 offset5">
    <%= link_to "Back", :back %>
  </div>
</div>

app/views/lists/shops.html.erb
<div class="container">
  <h2>The top places right now</h2>
  <% rank = 1 %>
  <% @venues.each do |v| %>
    <div class="results">
      <div id="rank">
        <%= rank %>
      </div>

      <div class="result">
        <div class="current_checkins">
          <p>Current <br>
            Check-ins</p>
          <p><%= v["hereNow"]["count"] %></p>
        </div>
        <div class="venue_details">
          <div><img src="<%= v["categories"][0]["icon"] %>"></div>
          <p><a href= "<%= v["canonicalUrl"] %>" target="blank"><%= v["name"] %></a></p>
          <p><%= v["location"]["address"] %></p>
          <p>Total Check-ins: <%= v["stats"]["checkinsCount"] %></p>
          <p><%= link_to "Social talk about this", "https://twitter.com/search?q=#{v["name"]}", :target => "_blank" %></p>
        </div>
            <!-- <p id="save">Get direction</p> -->
            <p><div class="btn btn-success"><%= link_to "Take me there ", "https://maps.google.com/maps/myplaces?ll=#{v["location"]["lat"]},#{v["location"]["lng"]}", :target => "_blank" %><i class="icon-map-marker icon-white"></i>
            </div></p>
      </div>
      <% rank += 1 %>
    </div>
  <% end %>
</div>

<div class="row">
  <div class="span7 offset5">
    <%= link_to "Back", :back %>
  </div>
</div>

app/views/pages/new.html.erb
<!-- START HEADER  -->
<div id="wrap">
        <div class="header-container">
            <header class="wrapper clearfix">
              <div class="ctaColumn">

                <!-- LOGO Replace // Replace Text with your App name for SEO, text is replaced with logo.png file  -->
                <h1>TrendVel</h1>
                </div>

                <!-- START IPHONE SLIDER -->
                <div class="fader">
                  <div class="flexslider1">
                    <ul class="slides">
                      <!-- INSERT IPHONE SLIDE  -->
                      <li><%= image_tag("Couch_Cachet_Slides-1.jpg")%></li>
                      <!-- INSERT IPHONE SLIDE  -->
                      <li><%= image_tag("Couch_Cachet_Slides-1.jpg")%></li>
                      <!-- INSERT IPHONE SLIDE  -->
                      <li><%= image_tag("Couch_Cachet_Slides-1.jpg")%></li>
                    </ul>
                  </div>
                </div>

                <!-- END HEADER -->
            </header>
        </div>





<h3>Unleash your travel!</h3>
<p><strong>Trendvel</strong> finds the coolest place in your location with realtime social</p>

<p>So what are you waiting for? Start your travel now.</p>
<ul>
  <li><h3><table><tr><td>Step 1: finds the coolest place in your location </td><td><a href='/clients/foursquare/new'><img src='https://playfoursquare.s3.amazonaws.com/press/logo/connect-black.png'/ style="padding-left: 10px;"></a></td></tr></table></h3></li>
  <li><h3 style="margin-top:10px;">Step 2: Check-in your trip and share your achievement.</h3></li>
</ul>

</div>